# Generated by Django 3.0.8 on 2020-07-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogInfo',
            fields=[
                ('blog_id', models.IntegerField(primary_key=True, serialize=False)),
                ('blog_title', models.CharField(max_length=100)),
                ('blog_content', models.TextField()),
                ('author_name', models.CharField(max_length=100)),
            ],
        ),
    ]
